services:
  - type: web
    name: django-web-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
